### ISSUE TITLE
Config_Fail

### ISSUE THREAD

**Issue by fatanifh** [LairdCP/BL652-Applications#12]
Hello,

I keep receiving Config_Fail during the provisioning stage in the Mesh example.
Please help!

**Comment by mtwooburn** [comment]
If you are using the BL652 and mesh, that is an extremely early mesh implementation.
Mesh is now only supported on our BL654 module which has a newer mesh implementation based on Nordic's v3 sdk.

**Comment by fatanifh** [comment]
I was able to resolve the issue.
Thank you. But is there a way i can use the new implementation on the BL652?

**Comment by mtwooburn** [comment]
Glad the issue was resolved.
The implementation on BL652 is based on a ver early v2 sdk from Nordic.
There is currently no plans to port the latest SDK onto the BL652
