### ISSUE TITLE
Firmware upgrades under Linux/Wine failing

### ISSUE THREAD

**Issue by koreymacdougall** [LairdCP/BL652-Applications#7]
Does anyone have experience upgrading the firmware on the BL652 using BL65xUartFwUpgrade.exe, running under a Linux/Wine environment?  While trying to upgrade, as soon as I select the appropriate COM port, the upgrade utility crashes, with this error:

`Exceptipon EInOutError in module`  
`BL65xUartFwUpgrade.exe at 000150AB.`  
`Device read error.`

I've tried playing with permissions/owernship of /dev/ttyUSB0, wine registry settings, and a few other ideas, but can't seem to get around this.  Any help would be much appreciated.

**Comment by thedjnK** [comment]
Upgrading firmware via UART using WINE is not currently supported. Please contact our support email on cs-support@lairdtech.com for further details.
